### PR TITLE
fixed rails backend I18n translations and added fallbacks

### LINKED ISSUE #5606: Localization missing in spec/services/meeting_starter_spec.rb
[ It seems there is still a localization missing in spec/services/meeting_starter_spec.rb, line 40...

`moderatorOnlyMessage: "To invite someone to the meeting, send them this link:<br>#{url}",` ]

Further attempts showed that the localisation in 'app/services/meeting_starter.rb' is apparently not working (line 60f.):

`moderator_message = "#{I18n.t('meeting.moderator_message')}<br>#{room_url}"`
`moderator_message += "<br>#{I18n.t('meeting.access_code', code: access_code)}" if access_code.present?`

The English text is always returned here, regardless of the browser language.
BigBlueButton Server 2.7.3 (492)
Greenlight 3.1.0.2

### PR DESCRIPTION
**Pull request by SilentFlameCR**
Fixes #5606 and #5583 
On meeting start setting I18n language for moderatorMessage to user language and fallback language of en in case of any missing translations.

### CODE REVIEW

File: app/services/meeting_starter.rb [hunk 1]
```diff
@@ -57,7 +57,7 @@ def call
 
   def computed_options(access_code:)
     room_url = "#{root_url(host: @base_url)}rooms/#{@room.friendly_id}/join"
-    moderator_message = "#{I18n.t('meeting.moderator_message')}<br>#{room_url}"
+    moderator_message = "#{I18n.t('meeting.moderator_message', locale: @current_user.language.to_sym)}<br>#{room_url}"
     moderator_message += "<br>#{I18n.t('meeting.access_code', code: access_code)}" if access_code.present?
```
Comment (farhatahmad) [inline app/services/meeting_starter.rb:61]: Need to add it here as well

Comment (SilentFlameCR) [reply app/services/meeting_starter.rb]: I missed that thanks updated and pushed now!

**Review by farhatahmad — APPROVED** [review]
