### PR TITLE
GIT-2207: Fixed internal error caused by overflowing pages (Fixes #2207)

### LINKED ISSUE #2207: Minor bug - error 500 - user management
Hello, 

I got error 500 when I reject last pending user on page 2. Issue is reproducible viewing url: http://<server>/b/admins?tab=pending&page=2, when count of pending users is lower than size of page (default is 25). 

    Best regards  Pavel Polacek

### PR DESCRIPTION
**Pull request by KH-Amir-TN**
## Description

Greenlight uses 'Pagy' gem for a simpler and efficient pagination.
[Pagy](https://ddnexus.github.io/pagy/how-to.html#gsc.tab=0) default behavior to handle overflowing pages is to raise the ['Pagy::OverflowError'](https://ddnexus.github.io/pagy/extras/overflow#gsc.tab=0) exception causing the application to render the 500 internal error page caused by the 'rescue_from' method in the ApplicationController.
Many actions in the AdminsController logic uses the 'redirect_back' to redirect the client back to were the initiated the request which leads upon banning,unbanning,undeleting,... last users in the last page to redirect the client back to an overflow page causing Pagy to raise the OverflowError exception and the controller to rescue_from it by rendering the internal error view which explains what occurred with [#2207](https://github.com/bigbluebutton/greenlight/issues/2207).
## Testing Steps

1.  Created many users.
2. Updated their role to have the 'pending' state.
3. Start declining and approving users.
4. Observed the error with approving/declining the last user in the last page other than 1.
5. Confirmed the root cause by accessing overflown pages on several areas in the application (rooms,admin pannel,recordings...).

### CODE REVIEW

File: spec/pagy_spec.rb [hunk 1]
```diff
@@ -0,0 +1,43 @@
+# frozen_string_literal: true
```
Comment (farhatahmad) [inline spec/pagy_spec.rb:1]: I'm not quite sure these tests are needed. This just seems to be testing the gem itself, which isn't what we'd want to do

Comment (KH-Amir-TN) [reply spec/pagy_spec.rb:1]: I have added them to ensure that 'Pagy' is configured the right way.
If it's not configured in the 'last_page' overflow mode it will fail.
As for the last test I agree too.
Do you need me to remove the last test or all of the tests?

Comment (farhatahmad) [reply spec/pagy_spec.rb:1]: I'd personally just remove them all

Comment (KH-Amir-TN) [reply spec/pagy_spec.rb]: Alright, I've just removed the spec file.

**Review by farhatahmad — APPROVED** [review]
