### PR TITLE
GIT-1861: Fixed reset password and activation dead lock on users with terms unaccepted

### LINKED ISSUE #1861: Password reset not working when accepted_terms=f in db
When an existing user account has accepted_terms=f (for example, when re-acking terms after a Privacy Policy Change is required and everyone is set to f), GL does not update the reset_digest and reset_sent_at fields of the DB, while still sending out a (which is, then, of course not working).

While checking up on this, it might be good to see if 'email_verified' has a similar effect, and triggering a password_reset+mail verification if email_verified=f.

Will take a look at that issue somewhen later this or next week (mostly a reminder for myself and sharing the fun bug).

### PR DESCRIPTION
**Pull request by KH-Amir-TN**
## Description

Organizations using Greenlight (GL) may have certain policies, terms and conditions that they would require their users to accept in order to consume their platform services.
Users who don't accept these terms won't be able to access all of the platform features until they align with its values.
But a user with unaccepted terms doesn't necessary mean that they refuse them as mentioned in #1861 [Terms can change and users may be explicitly have their acceptance reset by administrators in order to force them to read the new changes and accept them.].
Users with local accounts who still haven't accepted the terms should remain able to:
1. Reset their passwords.
2. Verify their email address.
3. Edit their profile information and password.
But users won't be able to join or manage their rooms or rooms that were shared with them until they accept terms.
There were issues that prevented users with unaccepted terms from having capabilities mentioned above.
This pull request ensures the users ability to reset their password, verify their email and change their information and administrators ability to send reset password emails and update profiles for users with unaccepted terms.
This pull request also solves some other minor bugs in the upstream not directly related to #3081.

#### Password reset [FIXED][#1861]
1. User hadn't accept the terms.
2. User had forgotten their password and tries to reset it.
3. User receive the reset email.
4. User can't reset their password to login to accept the terms [dead lock].

### Account activation (email verification) [FIXED][#1861]
1. User have unaccepted terms (i.e. User signs up while no terms exist).
2. User receives the verification email.
3. Before verifying the email an administrator enables terms and conditions.
4. User can't activate their account [dead lock].

### User edit profile [FIXED][considered in same context with #1861]
1. User login with unaccepted terms.
2. User doesn't accept terms.
3. User access their edit profile space and attempt to update their information.
4. User can't update their information nor change their password.

Also:
### New email verification [FIXED][#3080]
1. A logged in active user or an administrator access the user edit profile panel.
2. An update request to the user email gets created.
3. User have their email updated without having to verify it.

### Secure password circumventing [FIXED][#3078]
1. User with old password logged in or an administrator access the user edit profile.
2. An administrative update upgrades the platform to add new password complexity policy.
3. User will have their `secure_password` set to `false` by default to force them to reset it upon the next login.
4. User or the administrator make an update on the user's information.
5. User gets their `secure_password` set to `true` and therefore they circumvent the password forced reset.

### Change password to a secure one [FIXED][#3079]
1. A logged in user with an insecure password access their edit profile space.
2. User attempts to change their password to a secure one without making a reset.
3. User changes their password without setting the `secure_password` flag to `true`.
4. User will be required to reset their secure password upon the next login.

This fixes #1861, #3080, #3079 , #3078  and enhances #3081.

**A references to issues was left with comments on parts of the pull request code to help ease the review and because of the extended description that made it difficult to refer here.**

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -100,16 +100,16 @@ def update
...
-      @user.update_attributes(email_verified: false) if user_params[:email] != @user.email
-
-      # Mark password as secure
-      @user.update(secure_password: true)
-
-      user_locale(@user)
-
-      if update_roles(params[:user][:role_id])
+    # Changing email doesn't deactivate the greenlight_account [FIXED].
+    old_user_email = @user.email
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:104]: Fixes #3080

File: app/controllers/users_controller.rb [hunk 2]
```diff
@@ -100,16 +100,16 @@ def update
...
+    if @user.without_terms_acceptance { @user.update_attributes(user_params) }
+
+      @user.without_terms_acceptance {
+        @user.update_attributes(email_verified: false) if user_params[:email] != old_user_email
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:108]: Fixes #3080

File: app/controllers/users_controller.rb [hunk 3]
```diff
@@ -100,16 +100,16 @@ def update
       params[:user][:name] = @user.name
       params[:user][:email] = @user.email
     end
-
-    if @user.update_attributes(user_params)
-      @user.update_attributes(email_verified: false) if user_params[:email] != @user.email
-
-      # Mark password as secure
-      @user.update(secure_password: true)
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:108]: Removed to fix #3078

File: app/controllers/users_controller.rb [hunk 4]
```diff
@@ -122,23 +122,22 @@ def update
...
-      else
-        # New passwords don't match.
-        @user.errors.add(:password_confirmation, "doesn't match")
-      end
+    if @user.authenticate(user_params[:old_password])
+      # Bad UX on client side [FIXED].
+      @user.assign_attributes user_params.slice(:password, :password_confirmation)
     else
       # Original password is incorrect, can't update.
-      @user.errors.add(:password, "is incorrect")
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:135]: Closes #3081

File: app/controllers/users_controller.rb [hunk 5]
```diff
@@ -122,23 +122,22 @@ def update
   # POST /u/:user_uid/change_password
   def update_password
     # Update the users password.
-    if @user.authenticate(user_params[:password])
-      # Verify that the new passwords match.
-      if user_params[:new_password] == user_params[:password_confirmation]
-        @user.password = user_params[:new_password]
-      else
-        # New passwords don't match.
-        @user.errors.add(:password_confirmation, "doesn't match")
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:131]: Closes #3081

File: app/controllers/users_controller.rb [hunk 6]
```diff
@@ -122,23 +122,22 @@ def update
...
+      # Lack of translation [FIXED]
+      @user.errors.add(:old_password, I18n.t("old_password_incorrect"))
     end
 
     # Notify the user that their account has been updated.
-    return redirect_to change_password_path,
-      flash: { success: I18n.t("info_update_success") } if @user.errors.empty? && @user.save
-
+    if @user.errors.empty? && @user.without_terms_acceptance {
+      @user.save && @user.update_attribute(:secure_password, true)
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:136]: Fixes #3079

File: app/controllers/users_controller.rb [hunk 7]
```diff
@@ -241,7 +240,7 @@ def check_user_signup_allowed
 
   def user_params
     params.require(:user).permit(:name, :email, :image, :password, :password_confirmation,
-      :new_password, :provider, :accepted_terms, :language)
+      :old_password, :provider, :accepted_terms, :language)
```
Comment (KH-Amir-TN) [inline app/controllers/users_controller.rb:243]: Closes #3081

File: app/models/user.rb [hunk 8]
```diff
@@ -51,7 +51,8 @@ class User < ApplicationRecord
 
   # Bypass validations if omniauth
   validates :accepted_terms, acceptance: true,
-                             unless: -> { !greenlight_account? || !Rails.configuration.terms }
+                             if: -> { greenlight_account? && Rails.configuration.terms },
+                             unless: -> { @bypass_terms_acceptance }
```
Comment (KH-Amir-TN) [inline app/models/user.rb:55]: Fixes #1861

File: app/models/user.rb [hunk 9]
```diff
@@ -126,7 +127,9 @@ def ordered_rooms
   # Activates an account and initialize a users main room
   def activate
     set_role :user if role_id.nil?
-    update_attributes(email_verified: true, activated_at: Time.zone.now, activation_digest: nil)
+    without_terms_acceptance {
+      update_attributes(email_verified: true, activated_at: Time.zone.now, activation_digest: nil)
+    }
```
Comment (KH-Amir-TN) [inline app/models/user.rb:132]: Fixes #1861

File: app/models/user.rb [hunk 10]
```diff
@@ -140,13 +143,15 @@ def self.hash_token(token)
   # Sets the password reset attributes.
   def create_reset_digest
     new_token = SecureRandom.urlsafe_base64
-    update_attributes(reset_digest: User.hash_token(new_token), reset_sent_at: Time.zone.now)
+    without_terms_acceptance {
+      update_attributes(reset_digest: User.hash_token(new_token), reset_sent_at: Time.zone.now)
+    }
```
Comment (KH-Amir-TN) [inline app/models/user.rb:148]: Fixes #1861

File: app/models/user.rb [hunk 11]
```diff
@@ -140,13 +143,15 @@ def self.hash_token(token)
...
     new_token
   end
 
   def create_activation_token
     new_token = SecureRandom.urlsafe_base64
-    update_attributes(activation_digest: User.hash_token(new_token))
+    without_terms_acceptance { update_attributes(activation_digest: User.hash_token(new_token)) }
```
Comment (KH-Amir-TN) [inline app/models/user.rb:154]: Fixes #1861

File: app/models/user.rb [hunk 12]
```diff
@@ -232,6 +237,13 @@ def locked_out?
     false
   end
 
+  def without_terms_acceptance
+    @bypass_terms_acceptance = true
+    block_res = yield
+    @bypass_terms_acceptance = false
+    block_res
+  end
```
Comment (KH-Amir-TN) [inline app/models/user.rb:245]: Fixes #1861

File: app/views/users/components/_password.html.erb [hunk 13]
```diff
@@ -18,11 +18,11 @@
...
       <div class="col-8">
-        <%= f.label :password, t("settings.password.old"), class: "form-label" %>
-        <%= f.password_field :password, class: "form-control #{form_is_invalid?(@user, :password)}", autocomplete: :off, required: true %>
+        <%= f.label :old_password, t("settings.password.old"), class: "form-label" %>
+        <%= f.password_field :old_password, class: "form-control #{form_is_invalid?(@user, :old_password)}", autocomplete: :off, required: true %>
         <br>
-        <%= f.label :new_password, t("settings.password.new"), class: "form-label" %>
-        <%= f.password_field :new_password, class: "form-control", autocomplete: :off, required: true %>
+        <%= f.label :password, t("settings.password.new"), class: "form-label" %>
+        <%= f.password_field :password, class: "form-control #{form_is_invalid?(@user, :password)}", autocomplete: :off, required: true %>
```
Comment (KH-Amir-TN) [inline app/views/users/components/_password.html.erb:25]: Closes #3081

File: app/views/users/components/_password_security.html.erb [hunk 14]
```diff
@@ -16,15 +16,15 @@
...
+      <li class="small text-muted p-1"><%=t("password_complexity.one_lower_case")%></li>
+      <li class="small text-muted p-1"><%=t("password_complexity.one_upper_case")%></li>
     </ul>
   </div>
   <div class="col">
     <ul>
-      <li class="small text-muted p-1">At least 1 number</li>
-      <li class="small text-muted p-1">At least 1 symbol</li>
+      <li class="small text-muted p-1"><%=t("password_complexity.one_digit")%></li>
+      <li class="small text-muted p-1"><%=t("password_complexity.one_sym")%></li>
```
Comment (KH-Amir-TN) [inline app/views/users/components/_password_security.html.erb:27]: Closes #3081

File: config/locales/en.yml [hunk 15]
```diff
@@ -490,6 +491,13 @@ en:
   password_empty_notice: Password cannot be empty.
   password_reset_success: Password has been reset.
   password_different_notice: Password Confirmation does not match.
+  old_password_incorrect: is incorrect
+  password_complexity:
+    minimum_len: At least 8 characters
+    one_lower_case: At least 1 lowercase character
+    one_upper_case: At least 1 uppercase character
+    one_digit: At least 1 number
+    one_sym: At least 1 symbol
```
Comment (KH-Amir-TN) [inline config/locales/en.yml:500]: Closes #3081

File: spec/rails_helper.rb [hunk 16]
```diff
@@ -78,3 +78,7 @@
   #
   config.include ActiveSupport::Testing::TimeHelpers
 end
+
+# A dummy text to ensure testing without 'terms and conditions'.
+# Tests that depends on 'terms and conditions' will set them on example run.
+Rails.configuration.terms = false
```
Comment (KH-Amir-TN) [inline spec/rails_helper.rb:84]: This ensures that tests will run without being influenced by the existence of `config/terms.md`.
Tests that are affected by the existence of terms will mock it's existence when needed.

**Review by KH-Amir-TN — COMMENTED** [review]
@farhatahmad I hope that this helps simplify your review.

File: app/controllers/users_controller.rb (hunk 3 above)
Comment (farhatahmad) [reply app/controllers/users_controller.rb:108]: Is this still needed with https://github.com/bigbluebutton/greenlight/pull/3101 merged?

File: app/controllers/password_resets_controller.rb [hunk 17]
```diff
@@ -52,12 +52,14 @@ def update
...
-      # Mark password as secure
-      @user.update(secure_password: true)
+    elsif @user.without_terms_acceptance { @user.update_attributes(user_params) }
+      @user.without_terms_acceptance {
+        # Clear the user's social uid if they are switching from a social to a local account
+        @user.update_attribute(:social_uid, nil) if @user.social_uid.present?
+
+        # Mark password as secure
+        @user.update(secure_password: true)
+      }
```
Comment (farhatahmad) [inline app/controllers/password_resets_controller.rb:62]: Is this still needed with https://github.com/bigbluebutton/greenlight/pull/3101 merged?

Comment (farhatahmad) [reply app/controllers/password_resets_controller.rb:62]: It's probably best to put up a new MR that works with the upstream code

Comment (KH-Amir-TN) [reply app/controllers/password_resets_controller.rb:62]: Alright, I'll get back to it ASAP and I'll notify you Inshallah.

**Review by farhatahmad — APPROVED** [review]
